package ring

// ToneType is ring type
type ToneType string

// ring tone types
const (
	ToneAt    = ToneType("at")
	ToneAu    = ToneType("au")
	ToneBg    = ToneType("bg")
	ToneBr    = ToneType("br")
	ToneBe    = ToneType("be")
	ToneCh    = ToneType("ch")
	ToneCl    = ToneType("cl")
	ToneCn    = ToneType("cn")
	ToneCz    = ToneType("cz")
	ToneDe    = ToneType("de")
	ToneDk    = ToneType("dk")
	ToneEe    = ToneType("ee")
	ToneEs    = ToneType("es")
	ToneFi    = ToneType("fi")
	ToneFr    = ToneType("fr")
	ToneGr    = ToneType("gr")
	ToneHu    = ToneType("hu")
	ToneIl    = ToneType("il")
	ToneIn    = ToneType("in")
	ToneIt    = ToneType("it")
	ToneLt    = ToneType("lt")
	ToneJp    = ToneType("jp")
	ToneMx    = ToneType("mx")
	ToneMy    = ToneType("my")
	ToneNl    = ToneType("nl")
	ToneNo    = ToneType("no")
	ToneNz    = ToneType("nz")
	TonePh    = ToneType("ph")
	TonePl    = ToneType("pl")
	TonePt    = ToneType("pt")
	ToneRu    = ToneType("ru")
	ToneSe    = ToneType("se")
	ToneSg    = ToneType("sg")
	ToneTh    = ToneType("th")
	ToneUk    = ToneType("uk")
	ToneUs    = ToneType("us")
	ToneUsOld = ToneType("us-old")
	ToneTw    = ToneType("tw")
	ToneVe    = ToneType("ve")
	ToneZa    = ToneType("za")
)
