package twiml

const (
	tagAutopilot  = "Autopilot"
	tagClient     = "Client"
	tagConference = "Conference"
	tagConnect    = "Connect"
	tagDial       = "Dial"
	tagEcho       = "Echo"
	tagEnqueue    = "Enqueue"
	tagGather     = "Gather"
	tagHangup     = "Hangup"
	tagIdentity   = "Identity"
	tagLeave      = "Leave"
	tagNumber     = "Number"
	tagParameter  = "Parameter"
	tagPause      = "Pause"
	tagPay        = "Pay"
	tagPlay       = "Play"
	tagPrompt     = "Prompt"
	tagQueue      = "Queue"
	tagRecord     = "Record"
	tagRedirect   = "Redirect"
	tagRefer      = "Refer"
	tagReject     = "Reject"
	tagSay        = "Say"
	tagSMS        = "Sms"
	tagSiprec     = "Siprec"
	tagStart      = "Start"
	tagStop       = "Stop"
	tagStream     = "Stream"
	tagSim        = "Sim"
	tagSip        = "Sip"
	tagTask       = "Task"
	tagResponse   = "Response"
	tagRoom       = "Room"
)
