on:
  pull_request:
    branches:
      - master
    paths:
      - 'twiml/**.go'
      - ".github/workflows/test.yml"

name: run test

jobs:
  test:
    name: run server test
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
    - name: set up
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
      id: go

    - name: Checkout
      uses: actions/checkout@v1

    - name: cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: download modules
      working-directory: .
      if: steps.cache.outputs.cache-hit != 'true'
      run: go mod download

    - name: run test
      working-directory: .
      env:
        TZ: Asia/Tokyo
      run: make test
